import type { HidingSpot } from '@hide-and-seek/shared';

export const MAPS = [
  {
    id: 'chattatamer',
    name: 'Chatta-Tamer',
    image: require('@/assets/images/maps/chattatamer.png'),
    hidingSpots: [
      {
        id: '1',
        name: 'Liquid',
        x: 100,
        y: 120,
        width: 140,
        height: 80,
        isOccupied: false,
      },
      {
        id: '2',
        name: 'Operator',
        x: 450,
        y: 100,
        width: 140,
        height: 80,
        isOccupied: false,
      },
      {
        id: '3',
        name: 'Satellite',
        x: 680,
        y: 140,
        width: 140,
        height: 80,
        isOccupied: false,
      },
      {
        id: '4',
        name: 'Changing',
        x: 660,
        y: 300,
        width: 140,
        height: 80,
        isOccupied: false,
      },
      {
        id: '5',
        name: 'Teleporter',
        x: 620,
        y: 580,
        width: 160,
        height: 80,
        isOccupied: false,
      },
      {
        id: '6',
        name: 'Room',
        x: 90,
        y: 450,
        width: 160,
        height: 80,
        isOccupied: false,
      },
      {
        id: '7',
        name: 'Growth',
        x: 90,
        y: 580,
        width: 160,
        height: 80,
        isOccupied: false,
      },
      {
        id: '8',
        name: 'Meeting',
        x: 280,
        y: 370,
        width: 160,
        height: 80,
        isOccupied: false,
      },
      {
        id: '10',
        name: 'Pool',
        x: 350,
        y: 540,
        width: 100,
        height: 120,
        isOccupied: false,
      },
      {
        id: '11',
        name: 'Library',
        x: 640,
        y: 440,
        width: 140,
        height: 80,
        isOccupied: false,
      },
      {
        id: '12',
        name: 'Doom',
        x: 280,
        y: 200,
        width: 80,
        height: 80,
        isOccupied: false,
      },
    ] as HidingSpot[],
  },
  {
    id: 'clown-city',
    name: 'Clown City',
    image: require('@/assets/images/maps/clown-city.png'),
    hidingSpots: [
      {
        id: '1',
        name: 'Dining',
        x: 100,
        y: 120,
        width: 170,
        height: 100,
        isOccupied: false,
      },
      {
        id: '2',
        name: 'Sleep',
        x: 380,
        y: 120,
        width: 100,
        height: 100,
        isOccupied: false,
      },
      {
        id: '3',
        name: 'Toilet',
        x: 505,
        y: 120,
        width: 100,
        height: 80,
        isOccupied: false,
      },
      {
        id: '4',
        name: 'Tree House',
        x: 690,
        y: 80,
        width: 150,
        height: 100,
        isOccupied: false,
      },
      {
        id: '5',
        name: 'Cinema',
        x: 590,
        y: 260,
        width: 160,
        height: 100,
        isOccupied: false,
      },
      {
        id: '6',
        name: 'Below Table',
        x: 70,
        y: 330,
        width: 150,
        height: 70,
        isOccupied: false,
      },
      {
        id: '7',
        name: 'Living Room',
        x: 50,
        y: 530,
        width: 170,
        height: 100,
        isOccupied: false,
      },
      {
        id: '8',
        name: 'Bed 1',
        x: 340,
        y: 470,
        width: 80,
        height: 60,
        isOccupied: false,
      },
      {
        id: '9',
        name: 'Bed 2',
        x: 340,
        y: 580,
        width: 80,
        height: 60,
        isOccupied: false,
      },
      {
        id: '10',
        name: 'Pool',
        x: 740,
        y: 590,
        width: 100,
        height: 110,
        isOccupied: false,
      },
      {
        id: '11',
        name: 'Kitchen',
        x: 380,
        y: 300,
        width: 80,
        height: 100,
        isOccupied: false,
      },
      {
        id: '12',
        name: 'Bedroom',
        x: 590,
        y: 420,
        width: 140,
        height: 100,
        isOccupied: false,
      },
    ] as HidingSpot[],
  },
  {
    id: 'pleasant-park',
    name: 'Pleasant Park',
    image: require('@/assets/images/maps/pleasant-park.png'),
    hidingSpots: [
      {
        id: '1',
        name: 'D-Bed',
        x: 120,
        y: 110,
        width: 120,
        height: 100,
        isOccupied: false,
      },
      {
        id: '2',
        name: 'Desktop',
        x: 320,
        y: 90,
        width: 120,
        height: 80,
        isOccupied: false,
      },
      {
        id: '3',
        name: 'Table 1',
        x: 300,
        y: 310,
        width: 100,
        height: 80,
        isOccupied: false,
      },
      {
        id: '4',
        name: 'Table 2',
        x: 110,
        y: 470,
        width: 120,
        height: 80,
        isOccupied: false,
      },
      {
        id: '5',
        name: 'Balcony',
        x: 80,
        y: 620,
        width: 150,
        height: 60,
        isOccupied: false,
      },
      {
        id: '6',
        name: 'E-Room',
        x: 300,
        y: 600,
        width: 140,
        height: 80,
        isOccupied: false,
      },
      {
        id: '7',
        name: 'Loundry',
        x: 670,
        y: 100,
        width: 120,
        height: 90,
        isOccupied: false,
      },
      {
        id: '8',
        name: 'Couch',
        x: 670,
        y: 430,
        width: 120,
        height: 120,
        isOccupied: false,
      },
      {
        id: '9',
        name: 'Blank',
        x: 670,
        y: 250,
        width: 120,
        height: 60,
        isOccupied: false,
      },
      {
        id: '10',
        name: 'Netfloux',
        x: 90,
        y: 280,
        width: 120,
        height: 60,
        isOccupied: false,
      },
    ] as HidingSpot[],
  },
];
